apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName}}
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.appName}}
  template:
    metadata:
      labels:
        app: {{ .Values.appName}}
    spec:
      containers:
      - name: {{ .Values.containerName}}
        image: "{{ .Values.containerImage }}:{{.Values.containerTag}}"
        ports:
        - containerPort: {{ .Values.containerPort}}
        volumeMounts:
        - mountPath: {{.Values.mountPath}}
          name: {{ .Values.volumename }}
      volumes:
      - name: {{ .Values.volumename }}
        emptyDir: {}
