appName: adservice
replicas: 2
containerName: ad-app
containerImage: ahmed0130/microservice-adservice
containerTag:  latest
containerPort: 9555
continerEnv:
- name: PORT
  value: 9555

serviceName: adservice
servicePort: 9555
