appName: cartservice
containerName: cart-app
containerImage: ahmed0130/microservice-cartservice
containerTag:  latest
containerPort: 7070
continerEnv:
- name: PORT
  value: "7070"        
- name: REDIS_ADDR
  value: "redis-cart:6379"

serviceName: cartservice
servicePort: 7070
