appName: emailservice
replicas: 2
containerName: emial-app
containerImage: ahmed0130/microservice-emailservice
containerTag:  latest
containerPort: 8080
continerEnv:
- name: PORT
  value: 8080

serviceName: emailservice
servicePort: 5000
