appName: recommendationservice
replicas: 2
containerName: recommendation-app
containerImage: ahmed0130/microservice-recommendationservice
containerTag:  latest
containerPort: 8080
continerEnv:
- name: PORT
  value: 8080
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"

serviceName: recommendationservice
servicePort: 8080
